// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEg-7GwWhVBcxVeRvBLAzhZnijW4yhWdc',
    appId: '1:1075247458972:web:4457708a9d0d98c60d9b59',
    messagingSenderId: '1075247458972',
    projectId: 'my-project-8493b',
    authDomain: 'my-project-8493b.firebaseapp.com',
    storageBucket: 'my-project-8493b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrmvFDViE7UkUH8d3NlWWlAS4g9JKOG_4',
    appId: '1:1075247458972:android:171c0b76635059850d9b59',
    messagingSenderId: '1075247458972',
    projectId: 'my-project-8493b',
    storageBucket: 'my-project-8493b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYXQiWwZhHSrFKfTjLgbw72A1RuNdeACQ',
    appId: '1:1075247458972:ios:c327b52e5ef79fc70d9b59',
    messagingSenderId: '1075247458972',
    projectId: 'my-project-8493b',
    storageBucket: 'my-project-8493b.appspot.com',
    iosClientId: '1075247458972-gfbtraqoveqqiaofddnjtjtbin5ae3q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYXQiWwZhHSrFKfTjLgbw72A1RuNdeACQ',
    appId: '1:1075247458972:ios:c327b52e5ef79fc70d9b59',
    messagingSenderId: '1075247458972',
    projectId: 'my-project-8493b',
    storageBucket: 'my-project-8493b.appspot.com',
    iosClientId: '1075247458972-gfbtraqoveqqiaofddnjtjtbin5ae3q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
